<?php 
return array (
  'site_name' => '微企',
  'site_title' => '微企-国内优秀的微信公众服务平台',
  'site_logo' => '/tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://v17.weiqimobile.com',
  'site_my' => '微企',
  'server_key' => 'bc9ed510a91c14331cf2f6ce4169807b',
  'server_topdomain' => 'weiqimobile.com',
  'connectout' => '',
  'ischeckuser' => 'true',
  'reg_needmp' => 'false',
  'reg_groupid' => '4',
  'reg_validdays' => '7',
  'router_key' => '2b79c282b0f365ca9782cceb499e6022',
  'ipc' => '湘ICP备13225014号',
  'site_qq' => '2943747028',
  'site_mp' => '13800000000',
  'baidu_map_api' => 'KWe2TezxgWBDms0PYjeXBZWt',
  'site_email' => '2943747028@qq.com',
  'keyword' => '微企国内最大的微信公众智能服务平台，八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。',
  'content' => '微企国内最大的微信公众智能服务平台，八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。',
  'countsz' => '',
  'copyright' => '微企',
);